name: Publish Next.js Package

on:
  push:
    branches:
      - main
    paths:
      - 'packages/nextjs/**'

jobs:
  publish:
    runs-on: ubuntu-latest
    permissions:
      contents: write
      issues: write
      pull-requests: write
      packages: write
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0
          persist-credentials: false

      - name: Setup Bun
        uses: oven-sh/setup-bun@v1
        with:
          bun-version: latest

      - name: Install dependencies
        run: bun install

      - name: Resolve workspace dependencies
        run: |
          node -e "
          const fs = require('fs');
          const path = require('path');
          const nextjsPackageJsonPath = path.resolve('packages/nextjs/package.json');
          const serverPackageJsonPath = path.resolve('packages/server/package.json');
          const nextjsPackageJson = require(nextjsPackageJsonPath);
          const serverPackageJson = require(serverPackageJsonPath);

          if (nextjsPackageJson.dependencies) {
            for (const [key, value] of Object.entries(nextjsPackageJson.dependencies)) {
              if (value.startsWith('workspace:')) {
                nextjsPackageJson.dependencies[key] = `^${serverPackageJson.version}`;
              }
            }
          }

          fs.writeFileSync(nextjsPackageJsonPath, JSON.stringify(nextjsPackageJson, null, 2));
          console.log('Updated dependencies in nextjs/package.json:', nextjsPackageJson.dependencies);
          "

      - name: Build
        run: bun run build --workspace=@cipher-auth/nextjs

      - name: Release
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}
          NPM_TOKEN: ${{ secrets.NPM_TOKEN }}
        working-directory: ./packages/nextjs
